# Generated by Django 3.0.1 on 2019-12-20 03:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaspurchase',
            name='cost_per_gallon',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datetime',
            field=models.DateField(),
        ),
    ]
