# Generated by Django 2.2 on 2019-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_maintenance_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
