# Generated by Django 2.2 on 2019-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_auto_20190505_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default=0, max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30),
        ),
    ]
