# Generated by Django 3.0.1 on 2020-01-16 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_auto_20200116_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('\\d{4}')]),
        ),
    ]
