# Generated by Django 3.0.2 on 2020-01-24 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0004_auto_20200116_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(error_messages={'invalid': 'Enter a valid year'}, max_length=4, validators=[django.core.validators.RegexValidator('\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='datetime',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gas.Car')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
