# Generated by Django 2.2 on 2019-05-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
    ]
