# Generated by Django 3.0.2 on 2020-01-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_auto_20200124_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaspurchase',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toll',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
