# Generated by Django 2.2 on 2019-05-06 02:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_car_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaspurchase',
            options={'ordering': ['odometer_reading']},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['odometer_reading']},
        ),
        migrations.AddField(
            model_name='maintenance',
            name='odometer_reading',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='cost_per_gallon',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='gallons',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='odometer_reading',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
