# Generated by Django 3.0.2 on 2020-01-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_auto_20200124_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nickname',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
