# Generated by Django 2.2 on 2019-05-06 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0007_auto_20190506_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
