# Generated by Django 3.0.2 on 2020-01-24 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0008_auto_20200124_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='nickname',
            field=models.CharField(max_length=90, null=True, validators=[django.core.validators.RegexValidator('\\S+|^$')]),
        ),
    ]
