# Generated by Django 2.2 on 2019-05-07 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0008_car_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaspurchase',
            options={'ordering': ['-odometer_reading']},
        ),
        migrations.AddField(
            model_name='gaspurchase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        ),
    ]
