# Generated by Django 2.2 on 2019-05-07 04:21

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    CarModel = apps.get_model('gas', 'Car')
    GasModel = apps.get_model('gas', 'GasPurchase')
    for row in GasModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    MaintModel = apps.get_model('gas', 'Maintenance')
    for row in MaintModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0009_auto_20190507_0414'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
