# Generated by Django 2.2 on 2019-05-07 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0010_auto_20190507_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(unique=True, primary_key=False)
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='id',
            field=models.IntegerField(unique=True, primary_key=False)
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='id',
            field=models.IntegerField(unique=True, primary_key=False)
        ),
        migrations.AlterField(
            model_name='gaspurchase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
