# Generated by Django 3.0.2 on 2020-01-24 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_owner_gas_purchase(apps, schema_editor):
    GasPurchase = apps.get_model('gas', 'GasPurchase')
    for gas_purchase in GasPurchase.objects.all():
        gas_purchase.owner = gas_purchase.vehicle.owner
        gas_purchase.save()

def set_default_owner_maintenance(apps, schema_editor):
    Maintenance = apps.get_model('gas', 'Maintenance')
    for maintenance in Maintenance.objects.all():
        maintenance.owner = maintenance.vehicle.owner
        maintenance.save()

def set_default_owner_toll(apps, schema_editor):
    Toll = apps.get_model('gas', 'Toll')
    for toll in Toll.objects.all():
        toll.owner = toll.vehicle.owner
        toll.save()

def reverse(aps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0010_auto_20200124_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaspurchase',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toll',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_owner_gas_purchase, reverse),
        migrations.RunPython(set_default_owner_maintenance, reverse),
        migrations.RunPython(set_default_owner_toll, reverse),
        migrations.AlterField(
            model_name='gaspurchase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
        ),
        migrations.AlterField(
            model_name='toll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)
        ),
    ]
