# Generated by Django 2.2 on 2019-05-07 05:02

from django.db import migrations, models
import sys


def get_car(model, old_id):
    return model.objects.get(id=old_id)


def fix_fks(apps, schema_editor):
    CarModel = apps.get_model('gas', 'Car')
    GasModel = apps.get_model('gas', 'GasPurchase')
    for row in GasModel.objects.all():
        row.new_vehicle = get_car(CarModel, row.vehicle_id)
        row.save(update_fields=['new_vehicle_id'])

    MaintModel = apps.get_model('gas', 'Maintenance')
    for row in MaintModel.objects.all():
        row.new_vehicle = get_car(CarModel, row.vehicle_id)
        row.save(update_fields=['new_vehicle_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0011_auto_20190507_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaspurchase',
            name='new_vehicle',
            field=models.ForeignKey(to='gas.Car', on_delete=models.CASCADE, null=True)
        ),
        migrations.AddField(
            model_name='maintenance',
            name='new_vehicle',
            field=models.ForeignKey(to='gas.Car', on_delete=models.CASCADE, null=True)
        ),
        migrations.RunPython(fix_fks),
    ]
