# Generated by Django 2.2 on 2019-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0012_fix_vehicle_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaspurchase',
            name='vehicle'
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='vehicle'
        ),
        migrations.RenameField(
            model_name='gaspurchase',
            old_name='new_vehicle',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='new_vehicle',
            new_name='vehicle',
        ),
    ]
