# Generated by Django 2.2 on 2019-05-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0013_fix_vehicle_fk_rename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gaspurchase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='id',
        ),
    ]
